source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PodDemoTwo_Example', :exclusive => true do
  pod "PodDemoTwo", :path => "../"
end

target 'PodDemoTwo_Tests', :exclusive => true do
  pod "PodDemoTwo", :path => "../"

  pod 'FBSnapshotTestCase'
end
